apiVersion: v1
items:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "bluegreen-pipeline"
  spec:
    source:
      type: "Git"
      git:
        uri: "http://github.com/Freddy-Montero/rails-webapp-ex/openshift/templates"
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    env:
    - name: COLOR
      value: blue
kind: List
metadata: []
